name: bitmask32
description: A simple approach to 32-bit bitmasks. Used to send arrays of bools. MongoDB is using bitmasks as its flags parameters.

version: 2.0.3
homepage: https://github.com/Moonspeaker/bitmask32

environment:
  sdk: ">=2.1.0 <3.0.0"

dev_dependencies:
  test: